
import { UserData, CalculatorResults, ScenarioResult } from '../types';
import { GROWTH_MULTIPLIERS } from '../constants';

export const calculateResults = (data: UserData): CalculatorResults => {
  const { currentEnquiries, avgClientSpend, conversionRate, isRecurring } = data;
  const closeRate = conversionRate / 100;

  const calculateScenario = (label: string, multiplier: number): ScenarioResult => {
    // Additional enquiries generated by ranking in top 3
    // We assume a minimum boost even if current is 0
    const additionalEnquiries = Math.max(5, Math.round(currentEnquiries * multiplier));
    const newCustomers = Number((additionalEnquiries * closeRate).toFixed(1));
    const monthlyRevenue = Math.round(newCustomers * avgClientSpend);

    // Calculate 12-month cumulative effect
    // If recurring, it's M1 + (M1+M2) + ...
    // If one-off, it's just MonthlyRevenue * 12
    let annualCumulativeRevenue = 0;
    const monthlyProjections: number[] = [];
    
    let runningTotal = 0;
    for (let month = 1; month <= 12; month++) {
      if (isRecurring) {
        // Each month we add 'newCustomers' who each pay 'avgClientSpend'
        // So month 1 revenue is newCustomers * Spend
        // Month 2 revenue is (newCustomers * 2) * Spend
        runningTotal += (newCustomers * month * avgClientSpend);
      } else {
        runningTotal += (newCustomers * avgClientSpend);
      }
      monthlyProjections.push(Math.round(runningTotal));
    }
    annualCumulativeRevenue = Math.round(runningTotal);

    return {
      label,
      additionalEnquiries,
      newCustomers,
      monthlyRevenue,
      annualCumulativeRevenue,
      monthlyProjections
    };
  };

  return {
    moderate: calculateScenario('Moderate Growth', GROWTH_MULTIPLIERS.MODERATE),
    average: calculateScenario('Average Performance', GROWTH_MULTIPLIERS.AVERAGE),
    overPerform: calculateScenario('Market Leader', GROWTH_MULTIPLIERS.OVERPERFORM)
  };
};
